/*
Tencent is pleased to support the open source community by making Face-2-Face Translator available.

Copyright (C) 2018 THL A29 Limited, a Tencent company. All rights reserved.

Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

let language = [
  {
    id: 0,
    lang_name: "中文",
    lang_content: "zh_CN",
    lang_to: [ "en_US", ],
    max_length:300,
    source_language:"输入文字",
    target_language:"输出文字",
    hold_talk:"长按说话",
    keyboard_input:"键盘输入",
    type_here:"输入文字",
    bg_content:"请输入翻译内容",
    record_failed:"录制失败",
    recognize_nothing:"请说话",
    time_left:"录音输入倒数",
    text_left:"剩余文本长度",
    prompt_time:"提示秒数",
    upload_failed:"上传失败",
    translating:"翻译中",
    text_limit:"限制长度",
    input_tip:"请输入有效文字",
    request_failed:"请求失败",
    delete_tip:"删除该项",
    cancel:"取消",
    bubble_tip:"请输入文本",
    bg_bubble:"正在听你说话",
    copy_source_text: "复制原文",
    copy_target_text: "复制译文",
    delete_item: "删除",
    exceed_network:"网络请求失败",
    retry_network:"尝试重新连接",
    wait_last_record:"请等待翻译结束",
    access_auth:"请检查权限",
    access_network:"网络错误",
    login:"登录",
    navigationBarTitle:'微风拾音',
    numberline:'领取人数已达上线',
    stop:'已停止',
    canR:'可领取',
    receive:'领取',
    receiveSuccess:'真棒，任务领取成功',
    toast:'提示',
    setingToast:"请设置个人信息",
    reerrormsg:"每个任务单个用户最多接取1次，无法接取",
    start:'开始',
    taskNO:"任务编号",
    taskName:"任务名称",
    entryCount:"词条个数",
    agearray: [{ key: '1', value: '儿童(1-9)' }, { key: '2', value: '少年(10-17)' }, { key: '3', value: '青年(18-40)' }, { key: '4', value: '中年(41-64)' }, { key: '5', value: '老年(65以上)' }],
    accentarray: [{ key: '1', value: '普通话' }],
    accentTypeArray: [{ key: '1', value: '南方口音' }, { key: '2', value: '北方口音' }, { key: '3', value: '两广口音' }, { key: '4', value: '东北口音' }],
    items: [
      { name: '1', value: '男' },
      { name: '2', value: '女' }
    ],
    age:"年龄段",
    sex:"性别",
    accent:"口音",
    accentType:"口音类型",
    language:"语言",
    save:"保存",
    savesucess:'保存成功',
    readToast:"请读第",
    readTime:'次',
    meters:"录音时距离手机",
    tabName: ['可领任务', '待做任务', '已完成任务','个人设置'],
    wait:'等待开始',
    recording:"按住录音",
    second:'秒',
    submit:"确定",
    stopwork:"该任务已经被停止",
    nspeed:"正常语速",
    fspeed:"快速语速",
    lowspeed:"慢速语速",
    fillInfo:"请填写全部个人信息"
  },
  {
    fillInfo:"Please fill in all personal information",
    lowspeed:"Slow speed",
    fspeed:"Fast speed",
    nspeed:'normal speed',
    stopwork:"The task has been stopped",
    wait:'hold button to begin ,release to stop',
    submit:"submit",
    second:'seconds',
    recording:"hold to record",
    meters:"away from mobile phone",
    navigationBarTitle: 'Breeze Pickup Platform',
    numberline: 'Recipient is full',
    stop: 'stop',
    canR:'Avilable',
    receive: 'receive',
    receiveSuccess: 'OK, Received successfully',
    toast: 'Prompt',
    setingToast: "Please set your personal information",
    reerrormsg: "You have already received this task",
    receiveWorkErrorMsg:'',
    start: 'start',
    taskNO: "Task NO.",
    taskName: "Task Name",
    entryCount: "Word Num",
    agearray: [{ key: '1', value: 'children(1-9)' }, { key: '2', value: 'juvenile(10-17)' }, { key: '3', value: 'youth(18-40)' }, { key: '4', value: 'Middle-age(41-64)' }, { key: '5', value: 'elderly(65以上)' }],
    accentarray: [{ key: '1', value: 'English' }],
    accentTypeArray: [{ key: '1', value: 'English' }],
    items: [
    { name: '1', value: 'man' },
    { name: '2', value: 'woman' }
    ],
    age:"age range",
    sex:"sex",
    accent:"accent",
    accentType:"accentType",
    language:"language",
    save:"save",
    savesucess:'save sucess',
    readToast:"Read twinkling word for",
    readTime:' time',
    tabName: ['NEW', 'TODO', 'COMPLETED','SETING'],
        id: 1,
    lang_name: "EN",
    lang_content: "en_US",
    lang_to: [ "zh_CN", ],
    max_length: 1800,
    source_language: "Source Language",
    target_language: "Target Language",
    hold_talk: "Hold To Talk",
    keyboard_input: "Keyboard",
    type_here: "Type here...",
    bg_content: "Please enter the content to be translated",
    record_failed: "Audio recording failed",
    recognize_nothing: "Nothing recognized",
    time_left: "Recording time left",
    text_left: "Inputing text left",
    prompt_time: "Prompt time",
    upload_failed: "Upload failed",
    translating: "Translating",
    text_limit: "Text length has reached the limit",
    input_tip: "Please enter valid text",
    request_failed: "Request failed",
    delete_tip: "Delete this item",
    cancel:"Cancel",
    bubble_tip:"Please input English content",
    bg_bubble:"Please speak English",
    copy_source_text: "Copy Source",
    copy_target_text: "Copy Target",
    delete_item: "Delete",
    exceed_network: "Network request failed",
    retry_network: "Retry connect",
    access_auth:"Please checkout authorization",
    access_network:"Network error",
    login:"Login",
  }
]

module.exports = {
  language: language
}
